---
# tasks file for ansible-role-miniconda
- name: Download Installer for Miniconda
  ansible.builtin.get_url:
    url: '{{ conda_installer_repo }}'
    dest: '{{ installation_directory }}/install-miniconda.sh'
    checksum: sha256:3190da6626f86eee8abf1b2fd7a5af492994eb2667357ee4243975cdbb175d7a
    mode: 0755
    owner: 1000
    group: 1000
    
- name: Create Conda Directory
  file:
    path: " {{ conda_home_dir }}"
    state: directory
    owner: "{{ conda_user_id }}"
    group: "{{ conda_group_id }}"
    mode: 0755

- name: Run the installer
  ansible.builtin.shell: "{{ installation_directory }}/install-miniconda.sh -b -u -p {{ conda_home_dir }}"
